19214: Removes internal couns of nominals and nulls on training
howsoai/howso-engine pull request #125
Opened 2024-02-15 19:44 UTC by howsoRes

2024-02-15 21:20 UTC, cademack requested changes

2024-02-15 21:20 UTC, cademack commented on trainee_template/analysis.amlg
> +										num_cases
rather than (- num_cases num_nulls) to get the amount of non-null cases, could we just do a (query_not_equals)?

2024-02-15 21:20 UTC, cademack commented on trainee_template/marginal.amlg
>  	#!UpdateNullCounts
This method should be renamed now imo

2024-02-16 19:16 UTC, cademack approved these changes, later dismissed

2024-02-16 19:16 UTC, cademack commented on trainee_template/get_cases.amlg
> +							num_nulls (compute_on_contained_entities (list (query_equals feature (null)) (query_count) ))
I figure we should include the (query_exists feature) here too.

2024-02-16 19:16 UTC, cademack commented on trainee_template/get_cases.amlg
> +							num_nulls (compute_on_contained_entities (list (query_equals feature (null)) (query_count) ))
oh actually maybe it isn't necessary here

2024-02-16 19:25 UTC, howsohazard commented on trainee_template/attribute_maps.amlg
> +				;nominal can be (null) because engine keeps track of class counts for a nominal
null signifies to use the global unique nominal count for the given label

2024-02-16 19:28 UTC, howsohazard commented on trainee_template/prediction_stats.amlg
> +							;the assoc of features that have nulls or may have nulls
add comment that null defaults to true to reduce cognitive load on reader

2024-02-16 19:28 UTC, howsohazard commented on trainee_template/react.amlg
> +					(!= (false) (get featureNullRatiosMap (list (first action_features) "has_nulls")) )
like other comment - comment null defaults to true

2024-02-16 19:30 UTC, howsohazard commented on trainee_template/train.amlg
> +					)
why is this here and not in analyze?

2024-02-16 20:52 UTC, howsohazard approved these changes

2024-02-16 21:02 UTC, merged