20088: Adds check to see whether filepath should be ignored based on env variable
howsoai/howso-engine pull request #160
Opened 2024-04-25 21:36 UTC by howsoRes

adds validation to create_subtrainee, load_subtrainee and save_subtrainee filepath parameter, that if the environment variable 
HOWSO_ENGINE_LIMITED_FS is set to true, the passed-in value for the parameter will be ignored, and the stored filepath value will be used instead.

2024-04-26 13:39 UTC, cademack approved these changes, later dismissed

2024-04-26 13:39 UTC, cademack commented on howso/hierarchy.amlg
> +						(assign (assoc ignore_filepath_parameter (true) ))
Is there any reason to not just directly assign over `filepath` here in the `(map)`? rather than ticking the flag and doing it just below?

2024-04-26 17:11 UTC, cademack approved these changes

2024-04-26 17:30 UTC, howsohazard requested changes
Not needed -- this should be handled elsewhere.

2024-04-29 14:05 UTC, howsoRes commented
not going to implement in engine but in a different layer

2024-04-29 14:05 UTC, closed without merging