20103: Refactors response output, MAJOR
howsoai/howso-engine pull request #165
Opened 2024-05-02 17:40 UTC by howsoRes

2024-05-02 18:23 UTC, cademack requested changes

2024-05-02 18:23 UTC, cademack commented on howso/hierarchy.amlg
> +						(list 1 "palyoad" "cases")
typo here on "payload" which looks like it was already there... might as well fix now

2024-05-02 20:09 UTC, cademack submitted a review, later dismissed

2024-05-02 20:15 UTC, fulpm commented on howso.amlg
> +				(assoc "details" (map (lambda (current_value )) errors) )
The error response should include a key `detail` that is a string or list of strings. Optimally, it should only be a list if there are more than one message.

2024-05-03 19:28 UTC, fulpm commented on howso.amlg
> +	; [ 0, { 'details': error_descriptions, 'code': error_code, 'errors': field_validation_details } ]
docstring also needs to be updated for `detail`

2024-05-08 18:29 UTC, cademack approved these changes

2024-05-08 18:42 UTC, merged