20501: Sparsifies confusion matrix, MAJOR
howsoai/howso-engine pull request #197
Opened 2024-06-12 13:34 UTC by howsoRes

sparsifies confusion matrix by accruing all counts that are not statistically significant into separate values. This changes the format output for 'confusion_matrix' when calling get_prediction_stats

2024-06-12 14:01 UTC, cademack requested changes
(Putting this so it is not merged on accident)

2024-06-12 15:07 UTC, cademack commented on howso/feature_residuals.amlg
> +						(lambda (or (get (current_value) (current_index))) )
an (or) with one argument? I don't understand what this is about, shouldn't the value be able to be evaluated as a boolean anyway?

2024-06-12 15:07 UTC, cademack commented on howso/feature_residuals.amlg
> +									(get (current_value) (current_index))
Will the zero for the class being predicted always be here? Or should this be wrapped with an `(or __ 0)`?

2024-06-12 15:07 UTC, cademack commented on howso/feature_residuals.amlg
> +				"leftover_correct" (+ (or total_leftover_correct_predictions))
More of these one-arg (or)'s, please enlighten me :)

2024-06-12 15:07 UTC, cademack commented on howso/feature_residuals.amlg
> +					(call !SparsifyConfusionMatrices (assoc
So this method returns the (assoc) with the other keys as well. If we want to return these to the users, I think we should document somewhere what they are/what they mean. (probably needed for get_prediction_stats and the react detail comments).

If we don't want to return those extra keys (leftover counts, other counts, etc), then I suppose there should be a (remove) somewhere below this

2024-06-13 12:33 UTC, howsoRes commented on howso/feature_residuals.amlg
> +				"leftover_correct" (+ (or total_leftover_correct_predictions))
numerify null if null

2024-06-13 12:38 UTC, howsoRes commented on howso/feature_residuals.amlg
> +						(lambda (or (get (current_value) (current_index))) )
good point, the 'or' isn't necessary here

2024-06-13 12:43 UTC, howsoRes commented on howso/feature_residuals.amlg
> +					(call !SparsifyConfusionMatrices (assoc
well yes, we'll need to update the api anyway.

currently it returns those extra keys when there are leftovers only, should it return those keys all the time instead?

2024-06-17 14:03 UTC, howsoRes commented on howso/feature_residuals.amlg
> +									(get (current_value) (current_index))
since satistically_insignificant_rows_map only contains values that have the predicted class, we don't need to wrap it

2024-06-18 16:45 UTC, howsohazard commented on howso/hyperparameters.amlg
> +	;Helper method for computing SDM, filters out counts below threshold and stores as probabilities correct instead.
For just computing SDM?  Would be better to spell out or mention the method(s) that it helps out

2024-06-18 16:48 UTC, howsohazard commented on howso/feature_residuals.amlg
> +					))
Should expose smallest_count_threshold.  also, what is the logic around 200 case ids?

2024-06-20 02:22 UTC, howsohazard commented on howso/feature_residuals.amlg
> +	; smallest_count_threshold: number, optional, default is 10. Applicable only to confusion matrices, the number of predictions a class should have
should name it something appropriate then -- maybe confusion_matrix_min_count?

2024-06-20 17:00 UTC, howsohazard approved these changes

2024-06-20 17:33 UTC, cademack approved these changes

2024-06-20 17:38 UTC, merged