18483: Adds exclude_novel_nominals_from_uniqueness_check flag to reacts, MINOR
howsoai/howso-engine pull request #59
Opened 2023-11-30 18:19 UTC by howsoRes

2023-11-30 20:12 UTC, cademack submitted a review, later dismissed

2023-11-30 21:24 UTC, howsohazard requested changes

2023-11-30 21:24 UTC, howsohazard commented on howso.amlg
> +	; exclude_replaced_features_from_uniqueness_check: optional, default false. If true will exclude features whose values will be replaced
substituted -- reflect the nomenclature elsewhere, either "substituted features" or "substituted values" as appropriate

2023-12-05 16:43 UTC, jdbeel approved these changes, later dismissed
I validated that this solves the issue locally, we can add in tests in Validator-Enterprise that continue to validate this as well. Would like either @howsohazard  or @cademack 's eyes on this as well, though.

2023-12-05 16:56 UTC, cademack submitted a review, later dismissed
Looks good, other than the comment typo I marked

2023-12-05 16:56 UTC, cademack commented on trainee_template/attribute_maps.amlg
> +					;else don't output anything, map-filtering out any values that don't have data_type defined
filtering out values that don't have "subtype" defined, not data_type

2023-12-05 20:31 UTC, cademack approved these changes

2023-12-05 20:37 UTC, howsohazard approved these changes

2023-12-05 20:37 UTC, merged