18717: Updates null count for features on train
howsoai/howso-engine pull request #74
Opened 2023-12-18 22:30 UTC by howsoRes

2023-12-18 22:34 UTC, calebwherry commented on trainee_template/train.amlg
> +									;if it hasn't been computed yet, create an assoc of num_nulls -> number of nuls for the feature
*nulls (last one)

2023-12-18 22:57 UTC, howsohazard requested changes

2023-12-18 22:57 UTC, howsohazard commented on trainee_template/train.amlg
> +				;update count of nulls for the feature after training
Break into separate method (train is already too long).  Make sure that case editing and removing updates this correctly as well; may be able to reuse the method.

2023-12-19 00:55 UTC, howsohazard commented on trainee_template/marginal.amlg
> +							(size (contained_entities (list (query_equals feature (null)))))
This should be a compute_on_contained_entities with a query_count, which is far more efficient in memory and performance.

2023-12-19 00:56 UTC, howsohazard commented on trainee_template/marginal.amlg
> +							(size (contained_entities (list (query_equals feature (null)))))
I found at least one other (size (contained_entities... in analyzing boundaries for a feature.

2023-12-19 03:36 UTC, howsohazard approved these changes

2023-12-19 03:39 UTC, merged